@startuml
'https://plantuml.com/object-diagram

object "<u>:Main</u>" as Main
object "<u> :CommandHandler</u>" as CommandHandler
object "<u> in:Scanner</u>" as Scanner
object "<u> appointment:Appointment </u>" as Appointment {
name = John Doe
nric = S123A
date = 18-11-2024
time = 18:00
}
object "<u> appointmentRecord:AppointmentRecord</u>" as AppointmentRecord
object "<u> record:Record </u>" as Record
object "<u> :FileHandler </u>" as FileHandler

Main --> Record
Main --> AppointmentRecord
Main --> FileHandler
Main --> CommandHandler
Main --> Scanner
CommandHandler --> FileHandler
CommandHandler --> AppointmentRecord
CommandHandler --> Record
AppointmentRecord --> Appointment

@enduml
