@startuml Appointment
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0
hide circle

interface Comparable

skinparam classAttributeIconSize 0
hide circle

Comparable <|... Appointment

class "Appointment" as Appointment {
- patientName : String
- patientNric : String
- time : LocalTime
- date : LocalDate
- consultationDuration : long = 30
- formatter : DateTimeFormatter = dd-MM-yyyy
+ getPatientName() : String
+ getPatientNric() : String
+ getDate() : LocalDate
+ getTime() : LocalTime
+ getConsultationDuration() : long
+ toString() : String
+ compareTo(other : Appointment) : int
}

class AppointmentRecord {}
class Main {}
class CommandHandler {}
class AppointmentRecord {}


CommandHandler --> Appointment : searches and modifies >
AppointmentRecord "1" o-- "many" Appointment
Main --> CommandHandler : calls >

@enduml