@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0
hide circle

class CommandHandler {
-{static} logger: Logger
+CommandHandler()
+help()
+add(input: String, records: Records)
+list(records: Records)
+edit(input: String, records: Records)
+editVisit(input: String, records: Records)
+delete(nric: String, records: Records)
+find(input: String, records: Records)
+exit(input: String)
+addVisit(input: String, records: Records)
+Appointment(input: String, appointmentRecord: AppointmentRecord)
+deleteAppointment(input: String, appointmentRecord: AppointmentRecord)
+listAppointment(appointmentRecord: AppointmentRecord)
+findAppointment(input: String, appointmentRecord: AppointmentRecord)
+deleteAppointment(appointmentRecord: AppointmentRecord)
-findNextFieldStart(input: String, currentIndex: int)
}

class Patient {
}

class Visit {
}

class Main {
}

class Records {
}

class AppointmentRecord {
}

CommandHandler --> Appointment : searches and modifies >
AppointmentRecord "1" o-- "many" Appointment
Main --> CommandHandler : calls >
Main --> FindVisit : calls >
CommandHandler --> Patient : searches and modifies >
FindVisit --> Visit : searches >
Records "1" o-- "many" Patient
Patient "1" o-- "many" Visit

@enduml