@startuml
'https://plantuml.com/class-diagram
class "Command Handler Class" {
-{static} logger: Logger
+CommandHandler()
+help(): void
+add(input: String, records: Records): void
+list(records: Records): void
+edit(input: String, records: Records): void
+editVisit(input: String, records: Records): void
+delete(nric: String, records: Records): void
+find(input: String, records: Records): void
+exit(input: String): void
+addVisit(input: String, records: Records): void
+Appointment(input: String, appointmentRecord: AppointmentRecord): void
+deleteAppointment(input: String, appointmentRecord: AppointmentRecord): void
+listAppointment(appointmentRecord: AppointmentRecord): void
+findAppointment(input: String, appointmentRecord: AppointmentRecord): void
+deleteAppointment(appointmentRecord: AppointmentRecord): void
-findNextFieldStart(input: String, currentIndex: int): int
}
@enduml