@startuml
'https://plantuml.com/class-diagram

class FileHandler {
  +{static} initFile(Records): void
  +{static} initFile(AppointmentRecord): void
  +{static} convertPatientToOutputText(Records): String
  +{static} convertPatientToOutputText(AppointmentRecord): String
  +{static} autosave(Records): void
  +{static} autosave(AppointmentRecord): void
  +{static} retrieveData(Records): void
  +{static} retrieveData(AppointmentRecord): void
  +{static} parseVisitInputString(visitString): Visit
  +{static} parseList(input): ArrayList<String>
}

@enduml