@startuml
'https://plantuml.com/class-diagram

class FindVisit {
  +{static} findVisitByIc(nric, records): void
  +{static} findVisitByDiagnosis(Diagnosis, records): void
  +{static} findVisitByMedication(Medication, records): void
}

@enduml