@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0
hide circle

class Main {
-{static} logger: Logger {readOnly}
+{static} main(args: String[]): void
}

class Patient {}
class Visit {}
class Main {}
class Records {}
class CommandHandler {}
class AppointmentRecord {}


CommandHandler --> Appointment : searches and modifies >
AppointmentRecord "1" o-- "many" Appointment
Main --> CommandHandler : calls >
CommandHandler --> Patient : searches and modifies >
Records "1" o-- "many" Patient
Patient "1" o-- "many" Visit
@enduml
