@startuml
'https://plantuml.com/sequence-diagram

actor Doctor
Doctor -> ":Main" ++
":Main" -> ":Record" **
activate ":Record"
":Record" --> ":Main" -- : record:Record
":Main" -> ":AppointmentRecord" **
activate ":AppointmentRecord"
":AppointmentRecord" --> ":Main" -- : appointmentRecord:AppointmentRecord
":Main" -> ":FileHandler" ++ : initFile(records)
":FileHandler" --> ":Main" -- :
":Main" -> ":FileHandler" ++ : initFile(appointmentRecords)
":FileHandler" --> ":Main" -- :
":Main" -> ":CommandHandler" ** :
activate ":CommandHandler"
":CommandHandler" --> ":Main" --: commandHandler:CommandHandler
Doctor -> ":Main" : appointment("n/John Doe, ic/S123A, date/18-11-2024, time/18:00")
":Main" -> ":CommandHandler" ++: commandHandler.appointment("n/John Doe, ic/S123A, date/18-11-2024, time/18:00")
":CommandHandler" -> ":CommandHandler" ++: commandHandler.extractName("n/John Doe, ic/S123A, date/18-11-2024, time/18:00")
":CommandHandler" --> ":CommandHandler" --: name = "John Doe"
":CommandHandler" -> ":CommandHandler" ++: commandHandler.extractNric("n/John Doe, ic/S123A, date/18-11-2024, time/18:00")
":CommandHandler" --> ":CommandHandler" --: nric = "S123A""
":CommandHandler" --> ":CommandHandler" ++: commandHandler.extractDate("n/John Doe, ic/S123A, date/18-11-2024, time/18:00")
":CommandHandler" --> ":CommandHandler" --: date = "18-11-2024""
":CommandHandler" -> ":CommandHandler" ++: commandHandler.extractTime("n/John Doe, ic/S123A, date/18-11-2024, time/18:00")
":CommandHandler" --> ":CommandHandler" --: time = "18:00"
":CommandHandler" -> ":AppointmentRecord" ++ : appointmentRecord.checkAvailability("18-11-2024, 18:00")
":AppointmentRecord" --> ":CommandHandler" -- : nextAvailableTime
group alt [nextAvailableTime == "18:00"]
    ":CommandHandler" -> ":Appointment" **
    activate ":Appointment"
    ":CommandHandler" -> ":Appointment" : new Appointment("John Doe", "S123A", "18-11-2024", "18:00")
    ":Appointment" --> ":CommandHandler" -- : appointment

    ":CommandHandler" -> ":AppointmentRecord" ++ : appointmentRecords.addAppointment(appointment)
    ":AppointmentRecord" --> ":CommandHandler" --
    else
end
":CommandHandler" -> ":FileHandler" ++ : FileHandler.autosave(appointmentRecords)
":FileHandler" --> ":CommandHandler" --
":CommandHandler" --> ":Main" --
deactivate ":Main"
@enduml