@startuml
'https://plantuml.com/sequence-diagram

actor Doctor
participant ":CommandHandler"

note over ":CommandHandler": Continuing from Part 1\nafter successful validation

":CommandHandler" -> ":CommandHandler" ++: extractSex(input)
return "Female"

":CommandHandler" -> ":CommandHandler" ++: extractDateOfBirth(input)
return LocalDate("01-11-1998")

":CommandHandler" -> ":CommandHandler" ++: extractPhoneNumber(input)
return "98097890"

":CommandHandler" -> ":CommandHandler" ++: extractHomeAddress(input)
return "Bukit Batok East Avenue 3"

":CommandHandler" -> ":CommandHandler" ++: extractDiagnoses(input)
return ["Gastric"]

":CommandHandler" -> ":CommandHandler" ++: extractMedications(input)
return ["Gaviscon", "Paracetamol"]

":CommandHandler" -> ":CommandHandler" ++: extractAllergies(input)
return ["Peanuts"]

":CommandHandler" -> ":CommandHandler" ++: extractMedicalHistories(input)
return ["Hypertension", "Breast Cancer"]

create ":Visit"
":CommandHandler" -> ":Visit"**: new Visit(visitDateTime, diagnoses, medications)
activate ":Visit"
":CommandHandler" <-- ":Visit": newVisit:Visit
deactivate ":Visit"

create "newPatient:Patient"
":CommandHandler" -> "newPatient:Patient"**: new Patient(name, nric, visits)
activate "newPatient:Patient"

"newPatient:Patient" -> "newPatient:Patient": setSex(sex)
"newPatient:Patient" -> "newPatient:Patient": setDateOfBirth(dateOfBirth)
"newPatient:Patient" -> "newPatient:Patient": setPhoneNumber(phoneNumber)
"newPatient:Patient" -> "newPatient:Patient": setHomeAddress(homeAddress)
"newPatient:Patient" -> "newPatient:Patient": setAllergies(allergies)
"newPatient:Patient" -> "newPatient:Patient": setMedicalHistories(medicalHistories)

":CommandHandler" <-- "newPatient:Patient": patient created
deactivate "newPatient:Patient"

":CommandHandler" -> ":Records" ++: addPatient(newPatient)
":Records" -> ":Records": patients.add(newPatient)
return

":CommandHandler" -> ":FileHandler" ++: autosave(records)
return

Doctor <-- ":CommandHandler": Patient Patricia Chan with NRIC S9870789B added.

@enduml