@startuml
actor Doctor

Doctor -> ":Main" ++:  add n/Patricia Chan ic/S9870789B p/98097890 d/Cough\n m/Antibiotics ha/Bukit Batok East Avenue 3 dob/01111998\n v/21-10-2024 18:00 al/Peanuts s/Female mh/Hypertension

":Main" -> ":Scanner"**: new Scanner()
activate ":Scanner"
":Main" <-- ":Scanner": in:Scanner
deactivate ":Scanner"

":Main" -> ":Records"**: new Records()
activate ":Records"
":Main" <-- ":Records": records:Records
deactivate ":Records"

participant ":FileHandler" as FileHandler <<class>>

":Main" -> FileHandler ++: initFile(records)
return

":Main" -> ":CommandHandler"**: new CommandHandler()
activate ":CommandHandler"
":Main" <-- ":CommandHandler": commandHandler:CommandHandler
deactivate ":CommandHandler"

":Main" -> ":Scanner" ++: nextLine()
return input

":Main" -> ":CommandHandler" ++: add(input, records)

":CommandHandler" -> ":CommandHandler" ++: findNextFieldStart(...)
return the endindex of next prefix

":CommandHandler" -> ":Records" ++: getPatients()
":CommandHandler" <-- ":Records": ArrayList<Patient>
deactivate ":Records"

alt Missing Name
    ":CommandHandler" --> ":Main": "Please provide the patient's name"
else Missing NRIC
    ":CommandHandler" --> ":Main": "Please provide the patient's NRIC"
else Missing Visit Date
    ":CommandHandler" --> ":Main": "Please provide a date for the patient's visit"
else Valid Input
    ":CommandHandler" --> ":Main": "Continue to patient creation..."
end

@enduml